name: test
on: workflow_dispatch
jobs:
  tryit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: echo
        run: echo "HI THERE"
  deploy:
    runs-on: ubuntu-latest
    needs: [tryit]
    environment:
      name: test1
      url: https://testspace.com
    steps:
      - uses: actions/checkout@v4
      - name: echo
        run: echo "DEPLOYING WITH CHECK"
